from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('closet/', views.ClothingItemList.as_view(), name='clothing_items_index'),
    path('closet/tops', views.TopsList.as_view(), name='clothing_items_tops'),
    path('closet/bottoms', views.BottomsList.as_view(), name='clothing_items_bottoms'),
    path('closet/fullbody', views.FullBodyList.as_view(), name='clothing_items_fullbody'),
    path('closet/accessories', views.AccessoriesList.as_view(), name='clothing_items_accessories'),
    path('closet/shoes', views.ShoesList.as_view(), name='clothing_items_shoes'),
    path('closet/new/', views.ClothingItemCreate.as_view(), name='add_clothing_item'),
    path('closet/<int:clothingitem_id>/add_photo/', views.add_clothing_item_photo, name='add_clothing_item_photo'),
    path('closet/<int:pk>/edit/', views.ClothingItemEdit.as_view(), name='edit_clothing_item'),
    path('closet/<int:pk>/delete/', views.ClothingItemDelete.as_view(), name='delete_clothing_item'),
    path('closet/<int:clothingitem_id>', views.clothing_items_detail, name='clothing_items_detail'),
    path('accounts/signup/', views.signup, name='signup'),
    path('outfits/', views.OutfitList.as_view(), name='outfits_index'),
    path('outfits/<int:outfit_id>', views.outfit_detail, name='outfits_detail'),
    path('outfits/new', views.OutfitCreate.as_view(), name='add_outfit'),
    path('outfits/<int:outfit_id>/add_photo/', views.add_outfit_photo, name='add_outfit_photo'),
    path('outfits/<int:pk>/edit/', views.OutfitEdit.as_view(), name='edit_outfit'),
    path('outfits/<int:pk>/delete/', views.OutfitDelete.as_view(), name='delete_outfit'),
    path('outfit_tracker/', views.OutfitTracker.as_view(), name='outfit_tracker'),
    path('outfit_tracker/new_entry/', views.DateCreate.as_view(), name='new_entry'),
    path('outfit_tracker/<int:pk>/edit_entry/', views.DateEdit.as_view(), name='edit_entry'),
    path('closet/<int:clothingitem_id>/assoc_color/<int:color_id>/', views.assoc_color, name='assoc_color'),
    path('closet/<int:clothingitem_id>/unassoc_color/<int:color_id>/', views.unassoc_color, name='unassoc_color'),
    path('closet/<int:clothingitem_id>/assoc_tag/<int:tag_id>/', views.assoc_tag, name='assoc_tag'),
    path('closet/<int:clothingitem_id>/unassoc_tag/<int:tag_id>/', views.unassoc_tag, name='unassoc_tag'),
    path('outfits/<int:outfit_id>/assoc_clothingitem/<int:clothingitem_id>/', views.assoc_clothingitem, name='assoc_clothingitem'),
    path('outfits/<int:outfit_id>/unassoc_clothingitem/<int:clothingitem_id>/', views.unassoc_clothingitem, name='unassoc_clothingitem'),
]