# Generated by Django 4.2.5 on 2023-09-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('T', 'Tops'), ('B', 'Bottoms'), ('F', 'Full Body'), ('A', 'Accessories'), ('S', 'Shoes')], default='T', max_length=1)),
                ('date_acquired', models.DateField(auto_now=True)),
                ('place_purchased', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size', models.CharField(max_length=4)),
            ],
        ),
    ]
