# Generated by Django 4.2.5 on 2023-09-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='clothingitem',
            name='colors',
            field=models.ManyToManyField(to='main_app.color'),
        ),
    ]
