# Generated by Django 4.2.5 on 2023-09-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tag_clothingitem_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('clothing_items', models.ManyToManyField(to='main_app.clothingitem')),
            ],
        ),
    ]
