# Generated by Django 4.2.5 on 2023-09-27 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutfitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.outfit')),
            ],
        ),
    ]
