# Generated by Django 4.2.5 on 2023-10-04 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_clothingitem_date_acquired_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='user',
        ),
    ]
